### ISSUE TITLE
1.7 bug spam in console

### ISSUE THREAD

**Issue by soldier711** [Leontss1Official/Anti.pro-Bug-Reporting-Updates#2]
This console error spams the full out the console, 2 diff errors https://hastebin.com/jedesokozu.php this and the other one https://hastebin.com/yalukuredu.css when running in 1.7

**Comment by PacketHandler** [comment]
The second error is being fixed. The first error is caused either from a plugin or your spigot. We will try resolving this error shortly

~leontss1

**Comment by soldier711** [comment]
I'm running 1.7.10 Paperspigot protocolhack (1.7.10 - 1.8) I dont want to share a plugin list publicly here, but it consits of 1.7 plugins

**Comment by PacketHandler** [comment]
Error has been fixed/
