### ISSUE TITLE
Suggestion to config.yml - Complete

### ISSUE THREAD

**Issue by Ismael-GT** [Leontss1Official/Anti.pro-Bug-Reporting-Updates#3]
Version: 1.8
Discord Name: IsmaelHG
Issue: suggestion
Proof of the issue: Not a issue
Spigot Custom: false
Screenshot / Videos: innecesary
Effects game-play: false

----
Hello,

In the config.yml add the possibilty for add an argument in the ban command: %check% 
I do not understand how this has not been added before, please add when you can.

**Comment by PacketHandler** [comment]
Hello! Thanks for the suggestion, I would like to inform you that adding the check in the ban command is not a good idea, as people will figure why they got banned, and end up bypassing it. So I dont want to make one. ATM, I might add an argument with a check UUID that is visible in the config only by the owner so it doesnt get any bypasses

Regards,
leontss1.
