### ISSUE TITLE
Heuristics false bans

### ISSUE THREAD

**Issue by imask3r** [Leontss1Official/Anti.pro-Bug-Reporting-Updates#4]
Format: imask3r
Version: 1.7-1.8
Discord Name: mask3r #6359
Issue: Heuristics false bans
Proof of the issue: https://gyazo.com/b2fc87bf5f6cd414261728b360c2e5d4
Spigot Custom: True (Our custom spigot (Veil Spigot))
Screenshot / Videos: https://gyazo.com/332b6e5d984b4c4255d98270ec2902d0 /
https://www.youtube.com/watch?v=oe0y9W6gAFw&feature=youtu.be
Effects game-play: True / They are getting all banned (270 users banned today...)

**Comment by PacketHandler** [comment]
This false-possitive has been fixed, thanks for reporting.
